[build]
  functions = "netlify/functions"
  publish = "build"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions."download"]
  included_files = ["netlify/functions/bin/yt-dlp/yt-dlp_linux"]
