[build]
  functions = "netlify/functions"
  publish = "build"
  command = "npm run build"  # Ejecuta el script de construcción en package.json

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS" 

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build.processing]
  functions = [
    "cp ./bin/yt-dlp/yt-dlp_linux ./netlify/functions/bin/yt-dlp/yt-dlp_linux",
    "ls -l ./netlify/functions/bin/yt-dlp",
    "chmod +x ./netlify/functions/bin/yt-dlp/yt-dlp_linux"
  ]
